name: Dynamic Docker Tags

on:
  workflow_dispatch:

jobs:
  docker_dynamic_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: show SHA
        run: echo "Commit SHA is $SHORT_SHA"

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --pasword-stdin

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-demo-app:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-demo-app:$SHORT_SHA .

      - name: Push latest tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-demo-app:latest

      - name: Push SHA tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-demo-app:$SHORT_SHA
