name: Linux Lab

on: workflow_dispatch

jobs:
  linux_job:
    runs-on: ubuntu-latest

    env:
      COURSE: DevOps
      TRAINER: Pancha

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Variables
        run: |
          echo "Course Name: $COURSE"
          echo "Trainer Name: $TRAINER"

      - name: System Information
        run: |
          echo "Hostname:"
          hostname

          echo "Kernel:"
          uname -r

          echo "Memory:"
          free -h

          echo "Disk:"
          df -h
