name: Secrets Demo

on: workflow_dispatch

jobs:
  secrets_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Normal Variable
        run: echo "Learning Github Actions"

      - name: Access Secret
        run: echo "Secret is ${{ secrets.My_SECRET }}"
